### PR TITLE
don't assign tables if virtual

### LINKED ISSUE #64: Update Script for Virtual submissions
### **Acceptance Criteria**

-Update script to ignore virtual submssions, since they'll be submitting a video and don't need to be assigned
-We'll have a selection in the devpost options that will indicate this: stay tuned for updates
-This involves understanding how the script works - you should look at the files in the `/api` folder to get an idea of where to begin

### PR DESCRIPTION
**Pull request by stcwang**
Closes #64 
- added a `virtual` instance variable to the `Projects` class in `seed_db.py`
- modified `parse_csv_internal` in `seed_db.py` to check the "Virtual" column in the CSV and assign `virtual` var accordingly (**TODO: update this part to match Devpost formatting**) 
- modified table assignment function in `server.py` to skip projects that are marked virtual 
- modified `sortByTableNumber` in `helpers.js` so that projects that are not assigned table numbers are sorted to the end 

To test, I modified one of the CSVs in `data`. Specifically, I added a "Virtual" column at the end and populated it with "Yes" or "No" for each project (since I don't know the Devpost format for the question, I just made it up so that I could test the rest). This is an example screenshot, where the project Swype was marked as virtual:

Screen Shot 2023-03-28 at 5 11 37 PM

### CODE REVIEW

**Comment by farisalipk** [comment]
Great work Stephanie!! When Devpost formatting is finalized, feel free to merge :)))

**Review by farisalipk — APPROVED** [review]

**Comment by cloudui** [comment]
You should have a conditional statement to check if Virtual exists; it returns an error for devpost files without the column. I'm going to do this since we're on a time crunch.

**Comment by stcwang** [comment]
> You should have a conditional statement to check if Virtual exists; it returns an error for devpost files without the column. I'm going to do this since we're on a time crunch.

I'm going to have to edit that line anyways when I get the actual Devpost file formatting so I can just add the check in then.

**Comment by cloudui** [comment]
Okay, sounds good. I'm just going to add a temporary placement in your PR for now, since I don't want it to break while I'm testing the older CSVs without the virtual column. 

Thanks 😄

**Comment by cloudui** [comment]
Alright, I made a lot of changes. I made the virtual field editable in the admin console, render a Virtual favicon for the table number in the project view lists, and return virtual column in most of the useful get requests in the API. Since this was all 'virtual' field stuff, I decided to do it all on this branch.

**Pull request merged**
